spring.application.name=gestionBienestar
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionBienestar
spring.datasource.username=postgres
spring.datasource.password=781253
spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:postgresql://localhost:5432/gestionBienestar
spring.datasource.username=postgres
spring.datasource.password=781253

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8090
spring.security.user.name=admin
spring.security.user.password=admin123